# Generated by Django 4.2.7 on 2023-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCR', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('client_number', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_address', models.TextField()),
                ('sender_reference', models.CharField(max_length=40)),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_address', models.TextField()),
            ],
        ),
    ]
