# Generated by Django 4.2.7 on 2023-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceReader', '0002_alter_invoice_ocr_alter_invoice_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='invoice_documents/')),
            ],
        ),
    ]
